### PR TITLE
Using existing VPC and subnets for new cluster

### PR DESCRIPTION
**Pull request by Zeppier**
# Description

Allows installing EKS cluster on existing VPC, if VPC ID and subnets are provided.

Apart from that externalized VPC creation, so it's now in the root folder, and not under EKS. Also renamed variables connected only to the creation of VPC to start with "vpc_". 

Also provided example to create EKS cluster for Clickhouse using existing VPC.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested on existing AWS environment with VPC. I also tested that existing functionality with VPC creation is working as expected.

## What is the current behavior?

There is no way to select existing VPC during the creation of the EKS cluster for Clickhouse using this module.

## What is the expected behavior?

 If create_vpc is set to false use vpc_id and subnets variables to create EKS cluster.

## What is the motivation / use case for changing the behavior?

Allowing users to re-use existing VPCs.

### CODE REVIEW

**Comment by ianaya89** [comment]
@Zeppier code and approach looks great. I will be testing this further tomorrow and will came up with a final feedback (probably some changes in variable name convention)

Thanks!

**Comment by ianaya89** [comment]
@Zeppier I am not able to complete the setup for the "create new VPC" use case. I get this error:
```
╷
│ Error: waiting for EKS Add-On (clickhouse-cluster-vpc-test:aws-ebs-csi-driver) create: timeout while waiting for state to become 'ACTIVE' (last state: 'DEGRADED', timeout: 20m0s)
│
│   with module.eks_aws.module.eks_blueprints_addons.aws_eks_addon.this["aws-ebs-csi-driver"],
│   on .terraform/modules/eks_aws.eks_blueprints_addons/main.tf line 2179, in resource "aws_eks_addon" "this":
│ 2179: resource "aws_eks_addon" "this" {
│
╵
```

Can you check if that works for you?

**Comment by Zeppier** [comment]
@ianaya89 just tried the default example:

image


It worked for me. The only change I made is replaced a source to make it work:

`  source = "../../"`

**Comment by ianaya89** [comment]
Plan work well for me as well but `apply` fails while trying to setup `aws-ebs-csi-driver`. I will keep debugging and post here whatever I find

**Comment by ianaya89** [comment]
@Zeppier I will close this for now. We can re-take it later.
Thanks!

**Pull request closed without merging**
